### ISSUE TITLE
TODO LIST - eosc website

### ISSUE THREAD

**Issue by joshkauffman** [eoscanada/eosc#49]
### Tech
- [x] Setup [eosc.app](http://eosc.app)
- [x] Sync eosc commands info from the software with eosc Commands section of the website

### Homepage
- [x] need logo
- [x] work on tagline
- [x] reformat how eosc appears in the header for EOSC NEWS
- [x] create header for Benefits section
- [x] add a video section
- [x] go through text associated to EOS Canada

### News
- [x] get the release updates into the site - 0.7.8+0.7.9 DRAFT DONE
- [x] get the infographic into the site

### Docs
- [x] go through the landing page - what do we want them to see when clicking first on Docs

- [x] About EOSC - reorder the list when first clicking
- [x] About EOSC - Overview
- [x] About EOSC - Features Overview
- [x] About EOSC - License - DRAFT DONE
- [x] About EOSC - Benefits
- [x] About EOSC - What is EOSC - DRAFT DONE

- [x] Getting Started - DRAFT DONE
- [x] Global Settings - Global Settings Overview
- [x] Global Settings - Environment Variable
- [x] Global Settings - Global Flags DRAFT DONE

- [x] eosc Commands - eosc Commands Overview
- [x] eosc Commands - forum DRAFT DONE
- [x] eosc Commands - get DRAFT DONE
- [x] eosc Commands - multisig DRAFT DONE
- [x] eosc Commands - system DRAFT DONE
- [x] eosc Commands - tools DRAFT DONE
- [x] eosc Commands - tx DRAFT DONE
- [x] eosc Commands - vault DRAFT DONE
- [x] eosc Commands - vote - DRAFT DONE
- [x] eosc Commands - version (need to create version?)

- [x] help - help
- [x] help - faq
- [x] help - community

## Global
- [x] go through all header sections of the Hugo files to ensure all metadata is correctly updated
